server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud-check/**
        - id: notification
          uri: lb://NOTIFICATION
          predicates:
            - Path=/api/v1/notification/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true