server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://postgres:5432/fraud
    username: reinosoft
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: false
    hibernate:
      ddl-auto: update
    show_sql: true
    open-in-view: false
  zipkin:
    base-url: http://zipkin:9411
